### ISSUE TITLE
GDSQLite Error: Can't make necessary folders for path (ERROR = 2)

### ISSUE THREAD

**Issue by usertodog** [2shady4u/godot-sqlite#31]
Hi. I'm new to Godot and to godot-sqlite. Thank you for creating this gdnative library.  I downloaded the latest and compiled successfully for Windows and Android. When using the libraries with the demo in Windows, everything seems to work fine, but when exporting it to Android (using emulator with android 10.0 from Android Studio), the demo test I did had some problems.  Here's a snippet of what I get:

![android_studio_logcat](https://user-images.githubusercontent.com/78389418/106530917-de367800-64b2-11eb-8772-e83a5e967771.PNG)

I believe the problem is coming from lines 74 to 88 from the gdsqlite.cpp when trying to create a directory.  I removed this piece of code/recompiled and it seems to resolve the problem but that's probably not what you want to do.

**Comment by 2shady4u** [comment]
Hello @usertodog 

Thanks for submitting this issue!
Some more questions to better isolate the issue:

- What is the value of the path variable you are using?
- Did you try this out with the demo-project? (without recompilation and just exporting the demo-project to Android?)

**Comment by usertodog** [comment]
For my demotest project, I was using these paths for Android:

db_name = OS.get_user_data_dir() + "/test"
json_name = OS.get_system_dir(3) + "/test_backup"

But I also tried the "demo.zip" from the latest releases without changes. I could not run that demo "as is" because I get errors in Godot:

![godot_parser_error](https://user-images.githubusercontent.com/78389418/106619456-3b274200-6536-11eb-9d11-a4e2d794b605.PNG)

I commented all cases of "tex_data" to move on, but I got another error:

![godot_dll_error_1](https://user-images.githubusercontent.com/78389418/106619985-c1dc1f00-6536-11eb-88d9-b68d1930dbf4.PNG)

![godot_dll_error_2](https://user-images.githubusercontent.com/78389418/106620010-c6a0d300-6536-11eb-9b41-47698bf9ec4b.PNG)

I believe this error may be due to having a bad dll (or may be a debug dll instead of release?).  This was running on windows.  I tried to export to Android emulator, but the demo just showed black screen for me.  So at this point, I compiled the source to generate my own .dll/.so to use.  Using my compiled .so for Android (x86), I get some green text show up, but it is not the full list.  The logcat generates similar error messages:

![android_studio_logcat_demo](https://user-images.githubusercontent.com/78389418/106621060-cce37f00-6537-11eb-88ff-27bf5c340fa8.PNG)

Thank you for any help and I hope this information is useful.

**Comment by 2shady4u** [comment]
What version of Godot are you using?
What version of Ubuntu are you using? (or are you using another distro of Linux)

The first error with the tex_data is to be expected I guess, not smart from me to leave it in like that.
Can be easily fixed by replacing the offending line by:
`var tex_data : Texture = texture.get_data().save_png_to_buffer()`

The second error is much more heinous :/
I double-checked the version on the Asset Library and that DLL seems to be fine. 😅 
Also I downloaded the demo and downloaded and everything seems to work fine 🤔 
![image](https://user-images.githubusercontent.com/42484461/106624087-94629600-6575-11eb-8447-bf3ed32a9df8.png)

Furthermore could you try to use "user://test" instead?
Also, if you have time, could you install this program:
https://github.com/lucasg/Dependencies/releases/tag/v1.10

This program checks dependencies of DLLs and will thus show any problems with missing dependencies (= the main cause of not being able to open the DLL) In my case it shows this:

![image](https://user-images.githubusercontent.com/42484461/106624587-1d79cd00-6576-11eb-9d4e-49490762bc94.png)

Thus, no missing dependencies! (in my case)

**Comment by 2shady4u** [comment]
All the builds can be found in Github Actions btw:

![image](https://user-images.githubusercontent.com/42484461/106625037-92e59d80-6576-11eb-9500-6dba3ac27d28.png)

So it should all be compiled in release mode and having a debug build cannot be the issue.

**Comment by usertodog** [comment]
The "Texture" change fixed the parser issue.  As for the dll issue,  I think it's the same as this issue:
[https://github.com/2shady4u/godot-sqlite/issues/20](url)

I opened dependencies app for both the "demo.zip" dll and my compiled dll.  I don't use this app, so I can't tell if anything is wrong besides my dll doesn't have all that the demo one does.

"demo.zip" dll:

![image](https://user-images.githubusercontent.com/78389418/106628471-74b07b00-653f-11eb-908a-042aee25cff9.png)

"my compiled dll":

![image](https://user-images.githubusercontent.com/78389418/106629221-3a93a900-6540-11eb-9093-fe59c496611f.png)

As for changing the path, I updated the demo to use:

![image](https://user-images.githubusercontent.com/78389418/106630666-a6c2dc80-6541-11eb-8dbe-758a9d8130c6.png)

But I still get the same errors and what looks to be partial green text:

![image](https://user-images.githubusercontent.com/78389418/106631348-4da77880-6542-11eb-85f5-b3f445558715.png)

I searched the internet and may be this is the cause? 

[https://godotengine.org/qa/1288/error-on-create-directory-on-exported-game](url)

**Comment by usertodog** [comment]
Sorry. I posted before seeing your last comment about the "release" mode not being the problem.

**Comment by usertodog** [comment]
I guess I should have noticed the zoom-in feature.  Here's what I got from Android Emulator zoomed in:

![image](https://user-images.githubusercontent.com/78389418/106635749-cd374680-6546-11eb-83f6-749859701ddc.png)

Still have the "**ERROR**: GDSQLite Error: Can't make necessary folders for path (ERROR = 2)" in the logcat.  This is just using the demo with the modified "texture" update and the change to the path to use "user://test".  The .so used was from the "demo.zip".

**Comment by 2shady4u** [comment]
If not too much trouble could you check what issues persists after switching to 3.2.3.stable.official?
Might not be the problem, but who knows 🤷‍♂️ 

The dependencies thing looks good, there are no missing dependencies! So this means the possibility of a 'debug' build can be removed. (If there's a debug build, you would get missing dependencies there)

What architecture does this Android Emulator use? And if possible could you check if there's a difference between arm7 and arm64?

**Comment by 2shady4u** [comment]
Wait the `Texture` variable is the wrong class, it should be this:
`var tex_data : PoolByteArray = texture.get_data().save_png_to_buffer()`

**Comment by 2shady4u** [comment]
Okay, I think the issue is my fault. I can't get it to work on Android either now!
I got the exact same issue.

**Comment by usertodog** [comment]
Sorry.  I don't have Discord.  I will see if I can make the PoolByteArray change and test it later.  As for the lines 74-88 changes, I may need to recompile it again and test as I have overwritten that .dll/,so.

**Comment by 2shady4u** [comment]
Test 1:
- I removed the offending part and now android works again 🥳 

![Screenshot_2021-02-02-19-06-19](https://user-images.githubusercontent.com/42484461/106643393-f7f6be80-6589-11eb-8c7a-9a115ce482fd.png)

**Comment by usertodog** [comment]
Nice.  
I haven't downloaded the latest Godot version 3.2.3.stable.official so it may explain why I get the error below.

![image](https://user-images.githubusercontent.com/78389418/106655383-e3e99780-655e-11eb-9a9d-c1b75ba177cd.png)

I've commented out the tex_data piece and exported it out to the emulator with the lines 74-88 commented out as such:

![image](https://user-images.githubusercontent.com/78389418/106655550-214e2500-655f-11eb-92a4-8ea6870df6ce.png)

This is what I get from the emulator:

![image](https://user-images.githubusercontent.com/78389418/106655910-991c4f80-655f-11eb-89a3-70f545a2c9e6.png)

I circled the "result:" that doesn't seem to work for me in the emulator, but it works in windows.

**Comment by 2shady4u** [comment]
@usertodog 

Two of those errors are normal errors of the demo project:
1.
`--> SQL error: no such table: company`
This is because we attempt to delete the table with the name `company`, but since the table is newly created, this table does not exist! 

2.
`--> SQL error: FOREIGN KEY constraint failed`
This is because the foreign actually doesn't exist as an example of what would happen if you try to do this.

However, the error that is an actual problem is the fact that the json-file `test_backup_old.json` is not found.
If this file would be properly copied, the `Invalid get index '0' (on base: 'Array')` would dissappear automatically.
- Is the `test_backup_old.json` actually included? Is it copied correctly to the `user://`-folder?

**Comment by usertodog** [comment]
@2shady4u 

So I think the demo with the changes to lines 74-88 works.  But to do the test, I changed the export to have read/write external storage so that it can export/import to the Download folder (this was a functionality I wanted to use).

I tested it by updating the demo to do this:
1. after insert of data, export_to_json as "_old"
2. update one record (in my case Paul) with some new info (in my case age=45, name=Paul 2)
3. after update, export_to_json as "_new"
4. the import_to_json then looks for the "_old" which is there now and loads the "_old" data

![image](https://user-images.githubusercontent.com/78389418/106671175-ad6a4780-6573-11eb-8777-924fa17f7fdf.png)

Here's the logcat now:
![image](https://user-images.githubusercontent.com/78389418/106670999-6b410600-6573-11eb-857c-08e3dc24d8ec.png)

**Comment by 2shady4u** [comment]
Hello, good news since those 3 errors are all errors that are added to the demo-project as examples. You can easily find the places at which they are triggered.

So lets re-iterate:
- The Android build has issues because `make_dir_recursive` can't be called due to Android permission issues.
- The Windows build doesn't want to run because...? Because of Godot being a different version? Or what's the status on that issue?

Those were the only 2 issues right?

**Comment by usertodog** [comment]
To summarize on my end:

1. The initial problem I had was because of the make_dir_recursive section (lines 74-88).  To my understanding, it does not have to do with Android permissions.  I believe it has to do with godot trying to access/create a directory but doesn't have a base to start creating the directory at as mentioned in this godot q&a below (for some reason I can't link the url).  https://godotengine.org/qa/1288/error-on-create-directory-on-exported-game

![image](https://user-images.githubusercontent.com/78389418/106680832-dfd07080-6584-11eb-8135-9a3b053a49da.png)

2. The Windows build didn't work because I was using Godot version 3.2.1.  I just switched to 3.2.3 and my Windows build works fine (when I say Windows build, I mean the build with lines 74-88 removed/commented).  

3. As for why I was using Android permissions, it is because I was not able to verify if my export to Android carried over the files in the data folder (ie. test.db, test_backup_new.json, and test_backup_old.json).  Without those data files exported to my emulator, the error of not being able to open test_backup_old.json occurred.  So to work around this, I changed the code to utilize the downloads directory to export/import (and to use this code, I had to make it so the app has the correct Android permissions):

![image](https://user-images.githubusercontent.com/78389418/106681585-69347280-6586-11eb-8ce2-f3f79064d557.png)

All in all, I think lines 74-88 are the problem and removing them fixed it for me.

**Comment by 2shady4u** [comment]
@usertodog 

I've commented out the offending part (since it also doesn't work in windows export 😭 ) for now and added some additional fixes.
I'll test the windows demo project, windows export (in both release and debug mode) and the android demo project.

If possible could you check if the new release (will put link here once it is up) solves the issue for you?

**Comment by usertodog** [comment]
@2shady4u 

I just downloaded the demo.zip from your link and it looks like I get errors for both running in Windows (Godot 3.2.3) and from export to Android emulator (android v10).  No modifications to anything.  Here's screenshot of emulator error and windows error:

![image](https://user-images.githubusercontent.com/78389418/106766540-98d39100-65ff-11eb-9916-26e2129ba419.png)

![image](https://user-images.githubusercontent.com/78389418/106766756-c6b8d580-65ff-11eb-8815-0722b46caee0.png)

![image](https://user-images.githubusercontent.com/78389418/106766845-e05a1d00-65ff-11eb-9997-ff2b6d8c358e.png)

**Comment by 2shady4u** [comment]
Just checked again on my end by downloading the demo.zip myself and opening it in both 3.2.3.stable.official and 3.2.1.stable.official.

In both cases it works on Android and on Windows for me.
(Except for the tex_data ofc. but I disabled that)

I'm really at a loss what is going on? I'm gonna try ask some more basic questions (that might sound stupid, but who knows?) questions:
- What version of Windows are you using? 10? And if so, is your Windows mayhaps horribly outdated? Are you using a VM?
- Do other DLLs available in the asset store work for you? Like could you check if the DLL downloadable in this repository works for you: https://github.com/2shady4u/godot-cpp-ci
- What is the version of the NDK toolkit you are using in this emulator? What is the architecture you are emulating?
- Could you try to install the Android build to an actual device? Using godot's Android exporting functionality. 
- Could you try to install the APK using the command line as described here:
https://stackoverflow.com/questions/51791960/the-apk-failed-to-install-error-could-not-parse-error-string

Please answer and/or try these things and tell me what's happening.

**Comment by usertodog** [comment]
All of this could be on my end only, but I don't know either.  

I'm using Windows 10 v10.0.17763 Build 17763.  Not a VM. I haven't tried any of the older asset versions, but I'll have to check those out later.
My NDK version should be fairly new:
Pkg.Desc = Android NDK
Pkg.Revision = 21.3.6528147
The emulator uses x86 architecture as far as I know.
Using adb install, I get this error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

As for the other items, I'll need a little time to compile and test.

**Comment by usertodog** [comment]
I'm not sure if I did this correctly, but here's my win64 dll I compiled from your version2.2 asset.  I had to do a git clone --recursive for the godot-cpp as it was empty.  My dll is a lot bigger in size than yours but it works for me (target=release). I haven't compiled for any other platforms.

https://github.com/usertodog/godot-sqlite2.2_win64.git

**Comment by 2shady4u** [comment]
That libgdsqlite.dll that you linked me works on my end 🤷‍♂️ 
The size is quite big... How did you compile this?
- What version of VS are you using? If not using Visual Studio, what compiler are you using? How many bits?
- Are you perhaps using 32-bit builds/windows? 😱  (That could explain a lot!!!!)

**Comment by usertodog** [comment]
I am using MSYS2 with MinGW 64-bit.  I'm not using VS.  I am using a different SCONSTRUCT file as what you have though.  I've uploaded it to my repository.  This SCONSTRUCT works for my setup.

scons platform=windows target=release bits=64 use_mingw=yes

**Comment by 2shady4u** [comment]
okay, probably some debug symbols that dont get stripped properly or something. Nothing to worry about I guess.

Could you try to run the godot-cpp-ci project that I linked?

**Comment by usertodog** [comment]
With no compiling and just using "\godot-cpp-ci-main\gdnative_cpp_example\demo" project in godot 3.2.3.  I still get the error although it doesn't crash.  

![image](https://user-images.githubusercontent.com/78389418/106794504-8e74bf80-661e-11eb-85b9-562b5ccc3476.png)

**Comment by 2shady4u** [comment]
And if try to export it to android (without recompiling) Do you get the same error as for the SQLite library?

**Comment by usertodog** [comment]
There was no export preset for Android in that project, so I just created one with x86 checked.  Exported it to the emulator and it installed fine.  It also ran fine as well (the little icon moved around a bit, not sure if that was suppose to happen).  Looking at the logcat, there were no godot errors (some warnings).

**Comment by 2shady4u** [comment]
Yeah, the icon should wiggle a bit, that's all that is supposed to happen.

The fact that android works for that repository makes me even more confused...
Let's summarize a bit again (only for the windows part):

We know that in both cases:
1. The DLL is exported in 64-bit mode
2. The OS is 64-bit Windows 10
3. Godot is version 3.2.3 and is NOT MONO

🤔 
Could you go back in time and test out the Windows version of this plugin for version 2.0, 1.9, 1.8, .... and see if it starts working again at some point? Mayhaps they messed something up in godot-cpp-repository

**Comment by usertodog** [comment]
Which plugin are you referring to for version 2.0, 1.9, 1.8?  Also, I won't have time to do this right away but I can try to test when I have a chance.

**Comment by 2shady4u** [comment]
> Which plugin are you referring to for version 2.0, 1.9, 1.8? Also, I won't have time to do this right away but I can try to test when I have a chance.

Godot-SQLite, since the other plugin doesn't have older versions.
If there's anything that I can do to replicate the error, please enlighten me because that would help immensely.

**Comment by usertodog** [comment]
I think I found the fix for the windows error.  I searched the internet and it looks like the problem is that my computer didn't have the 2019 VC Redistributable as stated here:

https://github.com/godotengine/godot-git-plugin/issues/20

Downloaded/installed and the "open_dynamic_library" error goes away.

**Comment by 2shady4u** [comment]
Damn, I had hoped exporting in release mode takes care of this, but I guess that's not the case...

Here's another closed issue that gives a solution then:
https://github.com/godotengine/godot-cpp/issues/434

I'll try compiling with the /MT flag tomorrow to see what that does.

**Comment by 2shady4u** [comment]
Here's the DLL compiled with the /MT flag:
[libgdsqlite.zip](https://github.com/2shady4u/godot-sqlite/files/5922117/libgdsqlite.zip)

Could you test it out? Please uninstall the VC redistributable again 😄

**Comment by usertodog** [comment]
That worked!

**Comment by 2shady4u** [comment]
Okay! That's great news! I'll see if I can push this change trough at some point. (Hopefully at the level of the godot-cpp repository)

That just leaves the x86 android issue to be solved right? 🤔

**Comment by usertodog** [comment]
I found the x86 Android problem.  I didn't realize that the demo.zip 2.2 project doesn't have the x86 architecture turned on.  I turned it on and exported as usual.  The problem went away.

**Comment by 2shady4u** [comment]
@usertodog 
I am closing this issue and opening a new one that describes the issue in due detail.
